version: "3.9"
services:
  studio:
    build: .
    ports:
    - "8080:8080"

  ideas-plaintext-language:
    image: "docker4ideas/ideas-plaintext-module"

  ideas-latex-language:
    image: "ideas-latex-module"

  nginx:
    image: docker4ideas/ideas_nginx
    ports:
      - "8081:8081"
