version: "3.3"
services:
  studio:
    image: docker4ideas/ideas-studio:1.5
    ports:
    - "8080:8080"
    volumes:
    - ./configuration/studio-configuration:/config
    - tmp:/tmp

  nginx:
    image: docker4ideas/ideas_nginx
    ports:
      - "8081:8081"

  ideas-plaintext-language:
    image: docker4ideas/ideas-plaintext-module:1.0

  ideas-dockerfile-language:
    image: docker4ideas/module-docker
    privileged: true

  ideas-latex-language:
    image: docker4ideas/latex-module
    volumes:
     - tmp:/tmp

  ideas-dockercompose-language:
    image: docker4ideas/module-docker-compose
    privileged: true
    environment:
      - ONE_USER_MODE=false

volumes:
  tmp:
