version: "3.5"
services:

  nginx:
    image: docker4ideas/ideas_nginx
    ports:
      - "8081:8081"

  ideas-studio-develop:
    image: maven:3.8.4-openjdk-11-slim
    # command: bash -c "cd /ideas/repo && mvn install && tail -f /dev/null"
    command: bash -c "cd /ideas/repo && mvn install && cd /ideas/studio && mvn spring-boot:run"
    ports:
      - "8080:8080"
    volumes: 
      - .:/ideas/studio
      - ../ideas-repo:/ideas/repo
      - /tmp:/tmp
  
  ideas-latex-language:
    image: docker4ideas/latex-module
    # command: bash -c "cd /ideas/base-module && mvn install && tail -f /dev/null"
    command: bash -c "cd /ideas/base-module && mvn install && cd /ideas/latex-module && mvn spring-boot:run"
    volumes:
      - ../ideas-latex-module:/ideas/latex-module
      - ../ideas-base-module:/ideas/base-module
      - /tmp:/tmp
  
  ideas-plaintext-language:
    image: tomcat:9.0.16-jre8
    command: bash -c "cp /target/ideas-plaintext-language-0.7.war /usr/local/tomcat/webapps/ideas-plaintext-language.war && /usr/local/tomcat/bin/catalina.sh run"
    volumes:
      - ../ideas-plaintext-module/target:/target
