version: "3.8"
services: 
  nginx:
    image: docker4ideas/ideas_nginx
    ports:
      - "8081:8081"

  develop:
    image: docker4ideas/ideas-studio:develop_test
    ports:
      - "8080:8080"
    volumes: 
      - ../ideas-repo:/ideas-repo
      - .:/app